__title__ = 'bib2html'
__version__ = '1.0.0'
__license__ = 'MIT'
__author__ = 'Fabio D. Steffen'
__email__ = 'fabio.steffen@chem.uzh.ch'
__description__ = 'Convert bibtex references into HTML files '
__keywords__ = 'references, html, bibtex, citation'
__url__ = 'https://github.com/fdsteffen/bib2html'
__copyright__ = '2020, {}, University of Zurich'.format(__author__)
